name: Bug Report
description: File a bug report
title: "BUG : "
labels: ["bug"]
body:
  - type: input
    attributes:
      label: Numéro du dossier de la casserolle
      value: "ixD-"
  - type: textarea
    attributes:
      label: Description du problème
      description: (Vous pouvez y inclure des screenshots. Décrivez le problème du mieux que vous pouvez. Inscrivez le message d'erreur affiché s'il y a lieu.)
  - type: input
    attributes:
      label: Quand? La date et l'heure d'occurence du problème
      description: (Ceci nous permet parfois de retrouver l'erreur dans les logs)
  - type: textarea
    attributes:
      label: Comment le reproduire
      description: |
        "(Est-ce avec un usager particulier?)

        (Est-ce à l'envoi d'un formulaire? Un screenshot des data envoyées peut être utile)

        (URL exact de l'endroit où le problème survient)

        (Les informations d'environnement de l'utilisation, si possible)"
  - type: textarea
    attributes:
      label: Comportement attendu
      description: (Décrire ce qu'on s'attend d'avoir. Ça peut être très logique comme ça peut être un résultat de calcul complexe.)
  - type: textarea
    attributes:
      label: Autres notes
      description: (Autres notes jugées importantes à savoir)
  - type: textarea
    attributes:
      label: Solution possible
      description: |
        "(Si tu as une idée de ce qui cause le problème et/ou de ce qui pourrait le solutionner)

        (S'il faut corriger des données de production qui auraient été affectées, le mentionner)"
  - type: textarea
    attributes:
      label: Déploiement et notifications
      description: |
        "(S'il faut attendre avant de déployer le correctif, le mentionner)

        (S'il faut informer certaines personnes en particulier, par exemple quelqu'un d'autre que celui ou celle qui a créé l'issue, le mentionner)"
