name: Demande de modification
description: Demander une modification sur une fonctionnalité existante
title: "MODIFICATION : "
labels: ["modification", "enhancement"]
body:
  - type: input
    attributes:
      label: Numéro du dossier de la casserolle
      value: "ixD-"
  - type: textarea
    attributes:
      label: Description de la modification/amélioration
      description: |
        (Vous pouvez y inclure des screenshots. Décrivez du mieux que vous pouvez la modification à faire)
        (Dans la mesure du possible, distinguez le besoin (l'objectif à atteindre) du moyen (les éléments concrets qui sont attendus))
  - type: textarea
    attributes:
      label: À quel endroit?
      description: |
        (Fournissez l'URL de l'endroit où on doit faire la modification)
  - type: textarea
    attributes:
      label: Documents ou détails nécessaires
      description: |
        (Temps alloué pour le développement de la modification)
        (Images)
        (Pdf, texte a intégrer)
        (Maquette)
        (N'oubliez pas qu'un site peut-être bilingue)
  - type: textarea
    attributes:
      label: Scénarios de tests ou d'acception
      description: (Comment la feature sera-t-elle approuvée? Quels tests seront réalisés?)
  - type: textarea
    attributes:
      label: Autres notes
      description: (Autres notes jugées importantes à savoir)
